### PR TITLE
feat: add opensearch suggestion endpoints

### PR DESCRIPTION
**Pull request by dpeukert**
Hi, this PR implements two suggest endpoints based on the [OpenSearch specification](https://github.com/dewitt/opensearch/blob/master/mediawiki/Specifications/OpenSearch/Extensions/Suggestions/1.1/Draft%201.wiki), which enables browsers to use them for search suggestions.

### CODE REVIEW

**Comment by moson-mo** [comment]
Hi @dpeukert, thanks for your PR.

Hmm, sounds interesting. Do you have some specific use-case for this?  

If I understand [this](https://developer.mozilla.org/en-US/docs/Web/OpenSearch) correctly, it's meant for someone hosting a (search) website: They can basically add some OpenSearch description file (with the URL to the suggest endpoint) and advertise that to browsers via a link on their page as kind of browser plugin.

**Comment by moson-mo** [comment]
> What this PR does is add an endpoint that can be used by the user's browser

Yeah, I get that. 

> to return package name suggestions while searching using the custom search engine provided by the description

We already got that in AUR as well though (utilizing the current `suggest` call):

image

Now `archweb`  also has this. But they also invoke this via JS. So I'm wondering where that OpenSearch thing comes into play.

**Comment by dpeukert** [comment]
The OpenSearch description would enable you to basically do the same thing, but directly from the browser search bar, without having to go the AUR (you can set a keyword for the search engine, so if you typed `aur test` for example, you would get the same suggestion as in the screenshot).

The existing suggest would be fine for this, but unfortunately, the specification also requires the search term to be sent back as part of the response.

**Comment by moson-mo** [comment]
> but directly from the browser search bar

Aha. How do I enable this stuff?

It's not that "Add keyword for this Search..." (firefox) thing, is it? It does search, but not -auto-suggest while typing- for me (trying on archweb) 🤔 

image

**Comment by dpeukert** [comment]
It's not very intuitive to be honest, but you right click on the address bar, click 'Add "Arch Linux Packages"', then you go to Settings > Search > Search Shortcuts and add a keyword there.

**Comment by moson-mo** [comment]
> It's not very intuitive to be honest

Hehe, not really 😄. Thanks for the info.

Could you rebase? Just merged your other changes...

**Comment by dpeukert** [comment]
@moson-mo Should be ready to merge.

**Comment by moson-mo** [comment]
@dpeukert If you care about the commit signature, could you rebase to main and squash them commits instead? Otherwise I'll squash them... (sorry, I somwhat became allergic to merge commits)

**Comment by dpeukert** [comment]
No worries, rebased and squashed.

**Comment by moson-mo** [comment]
@dpeukert Thank you.

**Pull request merged**
